
import React from 'react';
import { 
  LayoutDashboard, 
  Users, 
  CreditCard, 
  DollarSign, 
  Menu, 
  ChevronDown, 
  Settings, 
  Database,
  FileText,
  MessageSquare,
  HelpCircle,
  MoreVertical,
  Clock,
  Search,
  Plus,
  Pencil,
  ChevronLeft,
  ChevronRight,
  ChevronsLeft,
  ChevronsRight,
  ArrowLeft,
  ArrowRight,
  X,
  Lock,
  Bot,
  ShieldCheck,
  Send,
  MessageSquarePlus,
  Eye,
  ArrowUpDown,
  Sun,
  Moon,
  Mountain,
  Leaf,
  Calendar,
  Filter
} from 'lucide-react';

export const Icons = {
  Dashboard: LayoutDashboard,
  Users: Users,
  Card: CreditCard,
  Dollar: DollarSign,
  Menu: Menu,
  ChevronDown: ChevronDown,
  Settings: Settings,
  Database: Database,
  File: FileText,
  Chat: MessageSquare,
  Help: HelpCircle,
  More: MoreVertical,
  Clock: Clock,
  Search: Search,
  Plus: Plus,
  Edit: Pencil,
  ChevronLeft: ChevronLeft,
  ChevronRight: ChevronRight,
  ChevronsLeft: ChevronsLeft,
  ChevronsRight: ChevronsRight,
  ArrowLeft: ArrowLeft,
  ArrowRight: ArrowRight,
  X: X,
  Lock: Lock,
  Bot: Bot,
  ShieldCheck: ShieldCheck,
  Send: Send,
  MessageSquarePlus: MessageSquarePlus,
  Eye: Eye,
  ArrowUpDown: ArrowUpDown,
  Sun: Sun,
  Moon: Moon,
  Mountain: Mountain,
  Leaf: Leaf,
  Calendar: Calendar,
  Filter: Filter
};